version: '3.8'

services:
  redis:
    image: redis:6

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             celery -A weather_app worker --loglevel=info &
             celery -A weather_app beat --loglevel=info &
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
